Refactor shell scripts vol 2
bmstu-iu8-cpp-sem-3/lab-xx-template pull request #13
Opened 2020-11-19 13:34 UTC by JarvisCraft

- [x] Используется shebang `#!/usr/bin/env bash` вместо `#!/usr/bin bash`
- [x] `checks.sh` теперь сканирует только директории с исходниками, указанными в проекте (раньше запуск скрипта на локальной машине сканировал также все сгенерированные директории)
- [x] убран параметр `--env-file`, который полагался на файл `.env`, генерировавшийся `genenv.sh`, который был удалён в be82e9f7e4bb35e50e5323b1fb5ec68ff9b1a0c7

2020-11-23 19:43 UTC, rusdevops requested changes

2020-11-23 19:43 UTC, rusdevops commented on scripts/checks.sh
> +find ./include/ ./scripts/ ./sources/ -name "*.cpp" -or -name "*.hpp" -or -name ".h" | grep -v "./tools/*"\
предложу заменить на `find . -name "*.cpp" -or -name "*.hpp" -or -name ".h" |  grep -v tools | grep -v builds`

2020-11-23 19:43 UTC, rusdevops commented on scripts/checks.sh
> +readonly FILTER=-build/c++11,-runtime/references,\
предложу без `readonly`

2020-11-23 19:43 UTC, rusdevops commented on scripts/coverage.sh
> +#!/usr/bin/env bash
👍

2020-11-23 19:43 UTC, rusdevops commented on scripts/tests.sh
> +
👍

2020-11-23 19:43 UTC, rusdevops commented on .travis.yml
> +        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/coverage.sh
👌

2020-11-23 20:11 UTC, JarvisCraft commented on scripts/checks.sh
> +readonly FILTER=-build/c++11,-runtime/references,\
Заменить на `declare -r` или просто убрать `readonly`? И, всё же, почему бы не оставить явный указатель на то, что это просто константный список? В теории, можно добавить включаемые флаги, но пока ведь оно только читается

2020-11-23 20:11 UTC, JarvisCraft commented on scripts/checks.sh
> +find ./include/ ./scripts/ ./sources/ -name "*.cpp" -or -name "*.hpp" -or -name ".h" | grep -v "./tools/*"\
Стоит ли? Момент в том, что IDE могут для своих целей использовать альтернативные пути (например, `cmake_build_debug/` по умолчанию у CLion), и создавать полный список исключений через цепочку из grep'ов и сложнее и менее читаемо (ну и, в общем, это выглядит более громоздко).
Что касается размещения исходников вне текущего списка директорий, мне кажется, это должно отсеиваться на этапе code-review.

2020-12-06 17:58 UTC, rusdevops commented on scripts/checks.sh
> +readonly FILTER=-build/c++11,-runtime/references,\
`declare -r`

2020-12-06 17:58 UTC, rusdevops commented on scripts/checks.sh
> +find ./include/ ./scripts/ ./sources/ -name "*.cpp" -or -name "*.hpp" -or -name ".h" | grep -v "./tools/*"\
тогда `grep -v "./tools/*"` можно убрать )

2020-12-06 19:24 UTC, JarvisCraft commented
Готово, все правки внёс

2020-12-07 13:44 UTC, rusdevops approved these changes

2020-12-07 13:44 UTC, merged

2020-12-07 13:45 UTC, rusdevops commented
@JarvisCraft спасибо, сейчас обновлю все лабораторные

2020-12-07 13:46 UTC, JarvisCraft commented
> @JarvisCraft спасибо, сейчас обновлю все лабораторные
> 

Спасибо за мердж :)